# Generated by Django 4.0.3 on 2022-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
