# Generated by Django 4.0.3 on 2022-04-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='newsList',
        ),
        migrations.AddField(
            model_name='news',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
