# Generated by Django 4.0.3 on 2022-04-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
