# Generated by Django 4.0.3 on 2022-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_category_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shortDetails',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
