# Generated by Django 4.0.3 on 2022-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_news_shortdetails_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='createdBy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
