# Generated by Django 4.0.3 on 2022-04-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='embeddedLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
