# Generated by Django 4.0.3 on 2022-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_news_embeddedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('embeddedLink', models.TextField()),
                ('showFrontPage', models.BooleanField(default=False)),
            ],
        ),
    ]
