# Generated by Django 4.0.3 on 2022-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_banner_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='embeddedLink',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='showFrontPage',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bannerImage'),
        ),
    ]
